import { apiFetchJson, getApiHref } from './client'
import type {
  ChannelPage,
  ChannelTab,
  CommentsResponse,
  FeedResponse,
  VideoDetails,
  YouTubePlaylistPage,
} from '../types'

export function fetchChannelPage(
  channelRef: string,
  tab: ChannelTab,
  page = 1,
  signal?: AbortSignal,
) {
  const params = new URLSearchParams({ tab, page: String(page) })
  return apiFetchJson<ChannelPage>(
    `/api/channels/${encodeURIComponent(channelRef)}?${params.toString()}`,
    { signal },
  )
}

export function fetchYouTubePlaylist(playlistId: string, page = 1, signal?: AbortSignal) {
  return apiFetchJson<YouTubePlaylistPage>(
    `/api/youtube-playlists/${encodeURIComponent(playlistId)}?page=${page}`,
    { signal },
  )
}

export function fetchVideoDetails(videoId: string, signal?: AbortSignal) {
  return apiFetchJson<VideoDetails>(`/api/videos/${encodeURIComponent(videoId)}`, { signal })
}

export function fetchComments(
  videoId: string,
  options: { pageToken?: string | null; order?: 'relevance' | 'time'; channelId?: string },
  signal?: AbortSignal,
) {
  const params = new URLSearchParams({ order: options.order ?? 'relevance' })
  if (options.pageToken) params.set('page_token', options.pageToken)
  if (options.channelId) params.set('channel_id', options.channelId)
  return apiFetchJson<CommentsResponse>(
    `/api/videos/${encodeURIComponent(videoId)}/comments?${params.toString()}`,
    { signal },
  )
}

export function fetchTrending(signal?: AbortSignal) {
  return apiFetchJson<FeedResponse>('/api/feed/trending', { signal })
}

export function fetchSubscriptionFeed(channelIds: string[], signal?: AbortSignal) {
  const params = new URLSearchParams({ channel_ids: channelIds.join(',') })
  return apiFetchJson<FeedResponse>(`/api/feed/subscriptions?${params.toString()}`, { signal })
}

export function getCaptionTrackUrl(videoId: string, lang: string, autoGenerated: boolean) {
  const params = new URLSearchParams({ lang, auto: String(autoGenerated) })
  return getApiHref(`/api/videos/${encodeURIComponent(videoId)}/captions?${params.toString()}`)
}

/** Video-only rendition for the HD player; it is paired with `getSplitAudioUrl`. */
export function getSplitVideoUrl(videoId: string, qualityId: string | null) {
  const query = qualityId ? `?quality=${encodeURIComponent(qualityId)}` : ''
  return getApiHref(`/api/stream/${encodeURIComponent(videoId)}/split/video${query}`)
}

export function getSplitAudioUrl(videoId: string) {
  return getApiHref(`/api/stream/${encodeURIComponent(videoId)}/split/audio`)
}
